"""init

Revision ID: b749c466d479
Revises: 
Create Date: 2026-04-21 15:26:41.169014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b749c466d479'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ImageType = postgresql.ENUM(
    'BASE',
    'MEDIA',
    name='image_type',
    create_type=False,
)


RestartPolicyType = postgresql.ENUM(
    'NO',
    'ALWAYS',
    'ON_FAILURE',
    'UNLESS_STOPPED',
    name='restart_policy_type',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
        CREATE TYPE image_type 
        AS ENUM ('BASE', 'MEDIA')
    """)
    op.execute("""
        CREATE TYPE restart_policy_type 
        AS ENUM ('NO', 'ALWAYS', 'ON_FAILURE', 'UNLESS_STOPPED')
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('branch', sa.String(length=256), nullable=False),
    sa.Column('bot_name', sa.String(length=256), nullable=True),
    sa.Column('image_type', ImageType, nullable=False),
    sa.Column('mem_reservation', sa.Integer(), nullable=False),
    sa.Column('mem_limit', sa.Integer(), nullable=False),
    sa.Column('cpu_quota_percents', sa.Integer(), nullable=False),
    sa.Column('cpu_period_percents', sa.Integer(), nullable=False),
    sa.Column('restart_policy', RestartPolicyType, nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_env', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.CheckConstraint('mem_limit <= 512', name='check_mem_limit_max'),
    sa.CheckConstraint('mem_limit >= mem_reservation', name='check_mem_limit_ge_reservation'),
    sa.CheckConstraint('mem_reservation >= 10', name='check_mem_reservation_min'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bots')
    # ### end Alembic commands ###

    op.execute("""
        DROP TYPE IF EXISTS RestartPolicyType
    """)
    op.execute("""
        DROP TYPE IF EXISTS ImageType
    """)
